import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "@/components/NavBar";
// import store from "@/store/store";
import { Providers } from "@/provider/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="dark">
      <body className={inter.className}>
        <Providers>
          <header>
            <NavBar />
          </header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
